using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using QRCoder;
using System.Drawing;
using System.Drawing.Imaging;

namespace Taskmate
{
    public static class MobileExporter
    {
        public static string GenerateMobileHTML(List<AssignmentResult> assignments, string title)
        {
            var html = new StringBuilder();
            
            html.AppendLine("<!DOCTYPE html>");
            html.AppendLine("<html lang='en'>");
            html.AppendLine("<head>");
            html.AppendLine("    <meta charset='UTF-8'>");
            html.AppendLine("    <meta name='viewport' content='width=device-width, initial-scale=1.0'>");
            html.AppendLine($"    <title>{title}</title>");
            html.AppendLine("    <style>");
            html.AppendLine(@"
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
            background: #f5f5f5; 
            padding: 10px; 
        }
        .header { 
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
            color: white; 
            padding: 20px; 
            border-radius: 10px; 
            margin-bottom: 15px; 
            text-align: center;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .header h1 { font-size: 24px; margin-bottom: 5px; }
        .header p { opacity: 0.9; font-size: 14px; }
        .person-card { 
            background: white; 
            border-radius: 10px; 
            padding: 15px; 
            margin-bottom: 10px; 
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .person-name { 
            font-size: 18px; 
            font-weight: bold; 
            color: #333; 
            margin-bottom: 8px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .task-count { 
            background: #667eea; 
            color: white; 
            padding: 4px 12px; 
            border-radius: 15px; 
            font-size: 14px;
        }
        .task-list { 
            list-style: none; 
            padding: 0; 
        }
        .task-item { 
            padding: 8px 12px; 
            margin: 5px 0; 
            background: #f8f9fa; 
            border-radius: 5px; 
            border-left: 3px solid #667eea;
        }
        .footer { 
            text-align: center; 
            padding: 20px; 
            color: #666; 
            font-size: 12px; 
        }
        @media (prefers-color-scheme: dark) {
            body { background: #1a1a1a; }
            .person-card { background: #2d2d2d; }
            .person-name { color: #fff; }
            .task-item { background: #3a3a3a; color: #fff; }
        }
            ");
            html.AppendLine("    </style>");
            html.AppendLine("</head>");
            html.AppendLine("<body>");
            
            // Header
            html.AppendLine("    <div class='header'>");
            html.AppendLine($"        <h1>📋 {title}</h1>");
            html.AppendLine($"        <p>Generated: {DateTime.Now:MMMM dd, yyyy h:mm tt}</p>");
            html.AppendLine($"        <p>{assignments.Count} people, {assignments.Sum(a => a.TaskCount)} tasks</p>");
            html.AppendLine("    </div>");
            
            // Assignments
            foreach (var assignment in assignments.OrderBy(a => a.Person))
            {
                var tasks = assignment.Tasks.Split(new[] { ", " }, StringSplitOptions.RemoveEmptyEntries);
                
                html.AppendLine("    <div class='person-card'>");
                html.AppendLine("        <div class='person-name'>");
                html.AppendLine($"            <span>{assignment.Person}</span>");
                html.AppendLine($"            <span class='task-count'>{assignment.TaskCount} tasks</span>");
                html.AppendLine("        </div>");
                html.AppendLine("        <ul class='task-list'>");
                
                foreach (var task in tasks)
                {
                    html.AppendLine($"            <li class='task-item'>{task.Trim()}</li>");
                }
                
                html.AppendLine("        </ul>");
                html.AppendLine("    </div>");
            }
            
            // Footer
            html.AppendLine("    <div class='footer'>");
            html.AppendLine("        <p>Generated by Task Assigner</p>");
            html.AppendLine("        <p>© 2026 Task Assigner</p>");
            html.AppendLine("    </div>");
            html.AppendLine("</body>");
            html.AppendLine("</html>");
            
            return html.ToString();
        }

        public static string GenerateQRCode(string url, string outputPath)
        {
            try
            {
                using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
                using (QRCodeData qrCodeData = qrGenerator.CreateQrCode(url, QRCodeGenerator.ECCLevel.Q))
                using (QRCode qrCode = new QRCode(qrCodeData))
                using (Bitmap qrCodeImage = qrCode.GetGraphic(20))
                {
                    qrCodeImage.Save(outputPath, ImageFormat.Png);
                    return outputPath;
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Failed to generate QR code: {ex.Message}");
            }
        }

        public static string SaveMobileExport(List<AssignmentResult> assignments, string title, string folderPath)
        {
            try
            {
                // Create folder if needed
                Directory.CreateDirectory(folderPath);
                
                // Generate HTML
                string htmlContent = GenerateMobileHTML(assignments, title);
                string htmlFileName = $"assignments_{DateTime.Now:yyyyMMdd_HHmmss}.html";
                string htmlPath = Path.Combine(folderPath, htmlFileName);
                File.WriteAllText(htmlPath, htmlContent);
                
                // Generate QR code pointing to the HTML file
                string qrFileName = $"qr_{DateTime.Now:yyyyMMdd_HHmmss}.png";
                string qrPath = Path.Combine(folderPath, qrFileName);
                GenerateQRCode($"file:///{htmlPath.Replace("\\", "/")}", qrPath);
                
                return htmlPath;
            }
            catch (Exception ex)
            {
                throw new Exception($"Failed to save mobile export: {ex.Message}");
            }
        }
    }
}