using System;
using System.Collections.Generic;
using System.Printing;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media;

namespace Taskmate
{
    public partial class PrintPreviewWindow : Window
    {
        private List<AssignmentResult> assignments;
        private string tag;

        public PrintPreviewWindow(List<AssignmentResult> assignments, string tag = "")
        {
            InitializeComponent();
            this.assignments = assignments ?? new List<AssignmentResult>();
            this.tag = tag ?? string.Empty;
            
            LoadPreview();
        }

        private void LoadPreview()
        {
            txtDate.Text = DateTime.Now.ToString("MMMM dd, yyyy - h:mm tt");
            txtTag.Text = string.IsNullOrEmpty(tag) ? "" : $"Tag: {tag}";
            txtFooter.Text = $"Generated by Task Assigner on {DateTime.Now:g}";
            
            icAssignments.ItemsSource = assignments;
        }

        private void btnPrint_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                PrintDialog printDialog = new PrintDialog();
                if (printDialog.ShowDialog() == true)
                {
                    // Create a flow document for printing
                    FlowDocument doc = CreatePrintDocument();
                    
                    IDocumentPaginatorSource idpSource = doc;
                    printDialog.PrintDocument(idpSource.DocumentPaginator, "Task Assignments");
                    
                    MessageBox.Show("Print job sent successfully!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Print failed: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private FlowDocument CreatePrintDocument()
        {
            FlowDocument doc = new FlowDocument
            {
                PagePadding = new Thickness(50),
                ColumnWidth = double.PositiveInfinity
            };

            // Title
            Paragraph title = new Paragraph(new Run("TASK ASSIGNMENTS"))
            {
                FontSize = 28,
                FontWeight = FontWeights.Bold,
                TextAlignment = TextAlignment.Center,
                Margin = new Thickness(0, 0, 0, 10)
            };
            doc.Blocks.Add(title);

            // Date
            Paragraph date = new Paragraph(new Run(DateTime.Now.ToString("MMMM dd, yyyy - h:mm tt")))
            {
                FontSize = 14,
                TextAlignment = TextAlignment.Center,
                Margin = new Thickness(0, 0, 0, 5)
            };
            doc.Blocks.Add(date);

            if (!string.IsNullOrEmpty(tag))
            {
                Paragraph tagPara = new Paragraph(new Run($"Tag: {tag}"))
                {
                    FontSize = 12,
                    TextAlignment = TextAlignment.Center,
                    Foreground = Brushes.Gray,
                    Margin = new Thickness(0, 0, 0, 30)
                };
                doc.Blocks.Add(tagPara);
            }

            // Assignments
            foreach (var assignment in assignments)
            {
                Section section = new Section();
                
                Paragraph personHeader = new Paragraph();
                personHeader.Inlines.Add(new Run(assignment.Person) { FontSize = 18, FontWeight = FontWeights.Bold });
                personHeader.Inlines.Add(new Run($" ({assignment.TaskCount} tasks)") { FontSize = 14, Foreground = Brushes.Gray });
                personHeader.Margin = new Thickness(0, 10, 0, 5);
                section.Blocks.Add(personHeader);
                
                Paragraph tasks = new Paragraph(new Run(assignment.Tasks))
                {
                    FontSize = 13,
                    Margin = new Thickness(20, 0, 0, 0),
                    TextAlignment = TextAlignment.Left
                };
                section.Blocks.Add(tasks);
                
                section.BorderBrush = Brushes.Black;
                section.BorderThickness = new Thickness(0, 0, 0, 1);
                section.Padding = new Thickness(10, 10, 10, 15);
                
                doc.Blocks.Add(section);
            }

            // Footer
            Paragraph footer = new Paragraph(new Run($"Generated by Task Assigner on {DateTime.Now:g}"))
            {
                FontSize = 10,
                TextAlignment = TextAlignment.Center,
                Foreground = Brushes.Gray,
                Margin = new Thickness(0, 30, 0, 0)
            };
            doc.Blocks.Add(footer);

            return doc;
        }

        private void btnCopy_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                string formatted = CsvExporter.FormatForClipboard(assignments);
                Clipboard.SetText(formatted);
                MessageBox.Show("Assignments copied to clipboard!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Copy failed: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void btnSavePdf_Click(object sender, RoutedEventArgs e)
        {
            MessageBox.Show("PDF export requires a PDF library. For now, use Print to PDF from the print dialog.", 
                "Info", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        private void btnClose_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }
    }
}